name: nisarqa
channels:
    - conda-forge
    - nodefaults  # force everything to come from conda-forge channel
dependencies:
    - cycler
    - h5py>=3
    - isce3>=0.16
    - matplotlib
    - numpy>=1.20
    - pillow
    - python>=3.8
    - ruamel.yaml
    - setuptools
    - shapely
